# Generated by Django 3.2.5 on 2021-07-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210721_0658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttributeValue',
            new_name='ProductAttribute',
        ),
    ]
