# Generated by Django 3.2.5 on 2021-07-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_productattributevalue_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_attribute_value', to='app.attributevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute_value')},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
    ]
